services:
  auth-faker:
    image: esenac/auth-faker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80

  auth-faker-tests:
    image: golang:1.18
    working_dir: /app
    volumes:
      - .:/app
    command: go test -v ./...

  service-tests:
    image: postman/newman
    volumes:
      - ./postman:/etc/newman
    command: run AuthFaker.postman_collection.json
    depends_on:
      - auth-faker

