project:
  name: auth-faker
  owner: platform
  scope: platform
  kind: services
  cost_allocation: platform
  pretty_name: Auth faker for service tests
templates:
  - name: crossenv
    terraform:
      version: ~>1.4
defaults:
  from:
    account: tools
    region: us-west-2
deployments:
  cross:
    cross:
      crossenv:
        template:
          name: crossenv
          variables:
            target_account_id: ssm::::/providers/aws/organization/main/accounts/tools/account/id
plan:
  - name: crossenv
    steps:
      - - cross.cross.crossenv
